version: '3.1'
services:
  dash:
    command: tail -f /dev/null
    image: sachinmalego/carpredictionthree:latest
    
    build:
      context: .
      dockerfile: .Dockerfile
    
    platform: linux/amd64

    ports:
      - 9001:80

    volumes:
       - ./source_code:/root/source_code
       - vscode-server:/root/.vscode-server

    environment:
      - HOST=0.0.0.0
      - PORT=80

    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.web-st125171-st125171.loadbalancer.server.port=8501
      # This config you domain name. By default, your subdomain is <service_name>-<folder_name>
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st125171-st125171.rule=Host(`st125171.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st125171-st125171.tls=true
      - traefik.http.routers.web-st125171-st125171.tls.certresolver=production
      - traefik.http.routers.web-st125171-st125171.entrypoints=websecure
    # This define network. You would need to keep it like this.

    networks:
      - default
      - traefik_default
    
    env_file:
      - .env

volumes:
  # needed by the devcontainer
  vscode-server:

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true
