version: '3.1'
services:
  dash:
    command: tail -f /dev/null
    image: sachinmalego/carpredictionthree:latest
    
    build:
      context: .
      dockerfile: .Dockerfile
    
    platform: linux/amd64

    ports:
      - 9001:80

    volumes:
       - source_code:/root/source_code
       - vscode-server:/root/.vscode-server

    environment:
      - HOST=0.0.0.0
      - PORT=80
    
    env_file:
      - .env

volumes:
  # needed by the devcontainer
  vscode-server:
