name: Dash App CI

on:
  push:
    branches:
      - main


jobs:
  # Step 1: Test the app using Docker
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image for testing
      - name: Build Docker image for testing
        run: docker build -t carpredictionasgthree -f .Dockerfile .

      # Run tests inside the Docker container
      - name: Run tests in Docker
        run: docker run carpredictionasgthree pytest

  build:
    runs-on: ubuntu-latest
    needs: test  # Build only after tests pass
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      # Log in to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build the Docker image for the app
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/carpredictionasgthree:latest -f .Dockerfile .
      # Push the image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/carpredictionasgthree:latest
  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install ssh-agent to manage the SSH key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.PASSPHRASE }}  # If the key is passphrase-protected

      # Create SSH config for proxy jump
      - name: Set up SSH config
        run: |
          echo -e "Host jump-proxy\n  HostName ${{ vars.PROXY_HOST }}\n  User ${{ secrets.USERNAME }}\n  Port 22\n  PasswordAuthentication yes\n" >> ~/.ssh/config
          echo -e "Host target-server\n  HostName ${{ vars.HOST }}\n  User ${{ secrets.USERNAME }}\n  ProxyJump jump-proxy\n" >> ~/.ssh/config

      # Install sshpass for password authentication through proxy
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Execute the deployment commands over SSH with proxy jump
      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.PROXY_PASSWORD }}" ssh -o StrictHostKeyChecking=no target-server << EOF
            docker pull sachinmalego/carpredictionasgthree:latest
            docker compose -f st125171/docker-compose.yaml down --remove-orphans
            docker compose -f st125171/docker-compose.yaml up -d
          EOF



    